server:
  port: 8080

spring:
  application:
    name: ORDERS

  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        register-health-check: true
        service-name: ${spring.application.name}
        #Use ip address rather than hostname during registration ,host主机名采用使用ip的方式注册
        prefer-ip-address: true
#        instance-id: ${spring.application.name}:${spring.cloud.client.ip-address}