server:
  port: 8761


spring:
  application:
    name: EUREKASERVER
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka,http://localhost:8762/eureka
    fetch-registry: false #关闭eureka启动时自动就注册本身
    register-with-eureka: false #指示此实例是否应向eureka server注册其信息以供其他人发现
#server:
    ##    enable-self-preservation: false #关闭自我保护
    ##    eviction-interval-timer-in-ms: 3000 #超时3s自动清除